//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiGK65CNTTCLC_65133958.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCVIEN
    {
        public string MaHV { get; set; }
        public string HoHV { get; set; }
        public string TenHV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string AnhDaiDien { get; set; }
        public string DiaChi { get; set; }
        public string MaDoiTuong { get; set; }
        public string Email { get; set; }
    
        public virtual DOITUONG DOITUONG { get; set; }
    }
}
